version: "3.8"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: auth_db  
    ports:
      - '5431:5432' 
    networks:
      - backend  
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth:
    build:
      context: auth 
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - backend
    restart: always
    depends_on: 
      db:
        condition: service_healthy
    environment:  
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=auth_db
      - DB_USER=postgres
      - DB_PASSWORD=12345

  wall:
    build:
      context: wall 
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    networks:
      - backend
    depends_on:
      - auth
    restart: always

networks:
  backend:
    driver: bridge