version: "3.8"

services:
  auth:
    build:
      context: auth 
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - backend
    restart: always
  wall:
    build:
      context: wall 
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    networks:
      - backend
    depends_on:
      - auth
    restart: always

networks:
  backend:
    driver: bridge